# Generated by Django 3.2.8 on 2021-10-18 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ydrm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='ydrm',
        ),
    ]
